version: '3'

services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.1
    ports:
      # The HTTP port
      - "80:80"
      # The TCP port
      - "44:44"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./traefik/routes.toml:/etc/traefik/routes.toml:ro
  envoy:
    # The official v2 Traefik docker image
    image: envoyproxy/envoy:v1.13.1
    ports:
      # The HTTP port
      - "10000:10000"
      # The Admin UI
      - "9901:9901"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
  application-1:
    image: quarkus/getting-started-jvm
    ports:
      - "8090:8080"
    labels:
      killable: true
  application-2:
    image: quarkus/getting-started-jvm
    ports:
      - "8091:8080"
    labels:
      killable: true
  mongo:
    image: mongo:4.0
    ports:
      - "27017:27017"
    # labels:
      # killable: true
