version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.1
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.file.filename=/etc/traefik/routes.toml --metrics.prometheus=true
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/routes.toml:/etc/traefik/routes.toml
  # A container that exposes an API to show its IP address
  whoami-1:
    image: containous/whoami
  whoami-2:
    image: containous/whoami
  application-1:
    build:
      context: ../../..
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8090:8080"
  application-2:
    build:
      context: ../../..
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8091:8080"
